# Generated by Django 5.0.6 on 2024-05-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trans_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
